// Generated by CoffeeScript 1.6.3
(function() {
  window.ToDoControl = function($scope) {
    $scope.items = [];
    $scope.items.push("a1");
    $scope.items.push("a2");
    $scope.items.push("a3");
    $scope.addItem = function() {
      var v;
      v = document.getElementById("input_item").value;
      return $scope.items.push(v);
    };
    return null;
  };

}).call(this);
